[package]
name = "bit_gossip"
version = "0.1.0"
edition = "2021"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
paste = "1.0"
rayon = { version = "1.10.0", optional = true }
